### ISSUE TITLE
Rust Analyzer

### ISSUE THREAD

**Issue by theduke** [figsoda/fenix#1]
Hey there.

Thanks for this project, very useful!

One additional wish: how about including nightly builds of rust-analyzer?

The official `rust-analyzer` version is sadly often very out of date.
The rustup component (`rust-analyzer-preview`) is also very far behind.

So a (ideally cached) version of frequent/nightly rust-analyzer builds would be very useful.

**Comment by figsoda** [comment]
I just added rust-analyzer nightly. It is briefly tested to work with the nightly version of the vscode extension (which I haven't packaged yet), but seems to be incompatible with the vscode extension in nixpkgs.

I still need to figure out how to package the nightly vscode extension, and I will add documentation after that.

For now, if you are using it as a flake, use `fenix.packages.x86_64-linux.rust-analyzer` assuming you are using x86_64-linux, if you are using it as a set of packages, use `fenix.rust-analyzer`, if you are using it as an overlay, use `pkgs.rust-analyzer-nightly`.

**Comment by theduke** [comment]
Awesome, thanks. I owe you a beer.

**Comment by theduke** [comment]
Regarding the VS Code extension: if the extension is available as a derivation, it can then be used with [`pkgs.vscode-extensions`](https://nixos.wiki/wiki/Vscode).

**Comment by figsoda** [comment]
I just added the nightly version of rust analyzer vscode extension. Feel free to reopen you met any problems.
