### ISSUE TITLE
Example of how to use this with `makeRustPlatform`

### ISSUE THREAD

**Issue by colemickens** [figsoda/fenix#3]
Hi, would it be possible to provide an example of how to use this with `makeRustPlatform` so that I can use a nightly toolchain with an existing Rust derivation that uses `rustPlatform`?

Thanks!

**Comment by figsoda** [comment]
I just added an [example](https://github.com/figsoda/fenix#examples).

**Comment by colemickens** [comment]
Thank you @figsoda, this worked great. I used in in my flake-powered overlay like this:

```nix
{
  jj = prev.callPackage ./pkgs/jj {
    rustPlatform = (prev.makeRustPlatform {
      inherit (inputs.fenix.packages.${prev.system}.minimal) cargo rustc;
    });
  };
}
```
