### ISSUE TITLE
example with `rustChannelOf`?

### ISSUE THREAD

**Issue by colemickens** [figsoda/fenix#6]
I am trying to build Veloren and it expects to build with its own declared rust-toolchain version.

I was previously trying to use `rustChannelOf` from `nixpkgs-mozilla`. Is that also available?

```
pkgs.rustChannelOf {
  rustToolchain = "${veloren.src}/rust-toolchain";
  sha256 = "sha256-...";
};
```

and `rustChannelOf` was coming from `nixpkgs-mozilla`. Can I replicate the same with `fenix`?

Thanks! And thanks for providing this.

**Comment by figsoda** [comment]
You can't specify a version with `fenix`. Though as an alternative you can lock the git revision.

**Comment by figsoda** [comment]
added `fromManifest`, `fromManifestFile`, and `toolchainOf` in https://github.com/nix-community/fenix/commit/d2c600db4bd5eb7df07d62b090fa43bbf7051323
